### ISSUE TITLE
Auto-increment the port if denied 8080

### ISSUE THREAD

**Issue by sdudnic** [alallier/reload#239]
I started this and fist start I had error

```
monitoring dir C:\peso\New folder
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1292:21)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
```

this is frustrating when you just install this package... Is there a possibility to auto-increment the port if the 8080 is denied?

**Comment by alallier** [comment]
Yeah that's a good idea, pull requests welcome.
