### ISSUE TITLE
Webpack server bundle can't find  '/reload-client.js'

### ISSUE THREAD

**Issue by tamis-laan** [alallier/reload#284]
I'm bundeling my server side code into a file called `server.js` that then serves my client side bundled code. I'm trying to use reload for easier reloading however I get the following error:

```
server_1         | node:fs:497
server_1         |   handleErrorFromBinding(ctx);
server_1         |   ^
server_1         | 
server_1         | Error: ENOENT: no such file or directory, open '/reload-client.js'
server_1         |     at Object.openSync (node:fs:497:3)
server_1         |     at Object.readFileSync (node:fs:393:35)
server_1         |     at eval (webpack:///./node_modules/reload/lib/reload.js?:24:25)
server_1         |     at new Promise (<anonymous>)
server_1         |     at reload (webpack:///./node_modules/reload/lib/reload.js?:13:10)
server_1         |     at module.exports (webpack:///./node_modules/reload/index.js?:4:10)
server_1         |     at Object.eval (webpack:///./server/app.js?:143:1)
server_1         |     at eval (webpack:///./server/app.js?:145:30)
server_1         |     at Object../server/app.js (/usr/src/app/build/server.js:11825:1)
server_1         |     at __webpack_require__ (/usr/src/app/build/server.js:29:30)
server_1         |     at eval (webpack:///./server/entry.js?:1:1)
server_1         |     at Object../server/entry.js (/usr/src/app/build/server.js:11968:1)
server_1         |     at __webpack_require__ (/usr/src/app/build/server.js:29:30)
server_1         |     at /usr/src/app/build/server.js:93:18
server_1         |     at Object.<anonymous> (/usr/src/app/build/server.js:96:10)
server_1         |     at Module._compile (node:internal/modules/cjs/loader:1091:14) {
server_1         |   errno: -2,
server_1         |   syscall: 'open',
server_1         |   code: 'ENOENT',
server_1         |   path: '/reload-client.js'
server_1         | }
```

**Comment by alallier** [comment]
The way you are including reload is not correct. Have you checked out the [sample app](https://github.com/alallier/reload-sample-app)?

If you're still having trouble let me know and I'd be happy to debug further with you!

**Comment by alallier** [comment]
Closing due to no feedback, happy to re-open with more information
