### ISSUE TITLE
(node:11916) UnhandledPromiseRejectionWarning: TypeError: route.match is not a function

### ISSUE THREAD

**Issue by RudimentalHack** [alallier/reload#286]
```yaml
(node:11916) UnhandledPromiseRejectionWarning: TypeError: route.match is not a function
        at processRoute (C:\Users\CG\Desktop\Github\VideoBox\node_modules\reload\lib\reload.js:220:35)
        at C:\Users\CG\Desktop\Github\VideoBox\node_modules\reload\lib\reload.js:25:32
        at new Promise (<anonymous>)
        at reload (C:\Users\CG\Desktop\Github\VideoBox\node_modules\reload\lib\reload.js:13:10)
        at module.exports (C:\Users\CG\Desktop\Github\VideoBox\node_modules\reload\index.js:4:10)
        at Object.<anonymous> (C:\Users\CG\Desktop\Github\VideoBox\index.js:37:1)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```
Code in question:
```js
   function processRoute (route) {
      // If reload.js is found in the route option strip it. We will concat it for user to ensure no case errors or order problems.
      const reloadJsMatch = route.match(/reload\.js/i)
      if (reloadJsMatch) {
        route = route.split(reloadJsMatch)[0]
      }
```

**Comment by alallier** [comment]
Can you show me how you are calling reload?

**Comment by CyberCDN** [comment]
I will do some more testing on this, and update you on my progress.
I am currently unable to provide how I'm calling it at this moment in time, but as stated above, I will inform you of more testing.

**Comment by alallier** [comment]
The `reload/reload.js` script tag needs to be on every HTML page if you want auto reloading on that page

**Comment by alallier** [comment]
Another option is to server side inject the reload script into every page. Which some applications layers/frameworks have successfully done like [Roosevelt](rooseveltframework/roosevelt)

Anyways we have an option issue for this currently #12. Therefore I'm going to close this issue. We can pickup the conversation over there
